using Robust.Client.UserInterface.CustomControls;
using Content.Shared._Forge.Newspapers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Content.Client._Forge.Paper;
using Robust.Client.Graphics;
using Robust.Shared.Log;
using Robust.Shared.Timing;

namespace Content.Client._Forge.Newspapers;

[GenerateTypedNameReferences]
public sealed partial class NewspaperCopyWindow : BaseWindow
{
    private bool _back;
    private NewspaperEdition? _edition;
    private readonly NewspaperPhotoRequest _photoRequest = new();
    private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    private Texture? _photo;
    private string _photoKey = "";
    private bool _photoUnavailable;
    private DocumentResourceCache<DocumentTextures>.Lease? _photoLease;
    private readonly DocumentTextureCacheSystem _cache = IoCManager.Resolve<IEntityManager>().System<DocumentTextureCacheSystem>();
    public event Action? OnImageRequested;

    public NewspaperCopyWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
        SideButton.OnPressed += _ =>
        {
            _back = !_back;
            PageView.Page = _back ? 1 : 0;
            if (_edition != null) PageView.SetContent(_edition, _photo);
            SideButton.Text = Loc.GetString(_back ? "newspaper-show-front" : "newspaper-show-back");
        };
    }

    public void UpdateState(NewspaperCopyUiState state)
    {
        _edition = state.Edition;
        if (_photoKey != state.PhotoKey)
        {
            _photoLease?.Dispose(); _photoLease = null; _photo = null;
            _photoKey = state.PhotoKey; _photoUnavailable = false;
        }
        if (_photoLease == null && _photoKey.Length > 0)
        {
            _photoLease = _cache.Photo(_photoKey);
            _photo = _photoLease?.Value.Background;
        }
        PageView.SurfaceAppearance = state.Surface;
        SideButton.Visible = state.Edition.Pages > 1;
        var available = Parent?.Size ?? new Vector2(1280, 900);
        var zoom = Math.Clamp(Math.Min((available.X - 64) / state.Edition.Width,
            (available.Y - 96) / state.Edition.Height), 0.1f, 1f);
        SetSize = new Vector2(state.Edition.Width * zoom + 8, state.Edition.Height * zoom + 40);
        PageView.Page = _back ? 1 : 0;
        PageView.SetContent(state.Edition, _photo);
        _photoRequest.SetTarget(_photoKey.Length == 0 ? -1 : state.Edition.PhotoId, 0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_edition != null && ScrollingContents.Width > 0 && ScrollingContents.Height > 0)
            PageView.PreviewScale = FitPageButton.Pressed
                ? Math.Clamp(Math.Min(ScrollingContents.Width / _edition.Width, ScrollingContents.Height / _edition.Height), 0.1f, 1f)
                : 1f;
        if (VisibleInTree && _photoRequest.TryRequest(_timing.RealTime, _photo != null || _photoUnavailable, out _))
            OnImageRequested?.Invoke();
    }

    public void ReceivePhoto(byte[] data)
    {
        try
        {
            if (_photoLease != null || _photoKey.Length == 0) return;
            _photoLease = _cache.Photo(_photoKey, data);
            _photo = _photoLease?.Value.Background;
            _photoUnavailable = _photoLease == null;
            if (_edition != null) PageView.SetContent(_edition, _photo);
        }
        catch (Exception e)
        {
            _photoUnavailable = true;
            Logger.ErrorS("newspaper", $"Cannot load newspaper photo: {e.Message}");
        }
    }

    protected override DragMode GetDragModeFor(Vector2 position)
    {
        const int edge = 12;
        var mode = DragMode.None;
        if (position.X < edge) mode |= DragMode.Left;
        else if (position.X > Width - edge) mode |= DragMode.Right;
        if (position.Y < edge) mode |= DragMode.Top;
        else if (position.Y > Height - edge) mode |= DragMode.Bottom;
        return mode == DragMode.None ? DragMode.Move : mode;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _photoLease?.Dispose();
        base.Dispose(disposing);
    }
}
