using Content.Client.UserInterface.Controls;
using Content.Client._Forge.Paper;
using Content.Shared._Forge.Newspapers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Log;
using Robust.Shared.Timing;
using System.Linq;
using System.IO;
using System.Numerics;

namespace Content.Client._Forge.Newspapers;

[GenerateTypedNameReferences]
public sealed partial class NewspaperDeskWindow : FancyWindow
{
    private NewspaperDeskUiState? _state;
    private NewspaperEdition _draft = new();
    private readonly List<NewspaperTemplatePrototype> _starters;
    private bool _loading;
    private bool _published;
    private bool _layout;
    private bool _pageSettings;
    private Button? _armedReplacement;
    private string? _armedReplacementText;
    private float _armedReplacementMinWidth;
    private TimeSpan _armedUntil;
    private NewspaperEdition? _savedDraft;
    private NewspaperEdition? _checkpoint;
    private NewspaperEdition? _pendingSave;
    private readonly List<NewspaperEdition> _undo = new();
    private readonly List<NewspaperEdition> _redo = new();
    private bool _restoring;
    private bool _publishPending;
    private TimeSpan _requestTime;
    private string? _captionNotice;
    private DialogWindow? _confirmation;
    private int _zoom;
    private int _page;
    private int _selected = -1;
    private int _template;
    private int _edition;
    private int _count = 1;
    private readonly Dictionary<int, Texture> _photos = new();
    private readonly HashSet<int> _unavailablePhotos = new();
    private readonly Dictionary<int, DocumentResourceCache<DocumentTextures>.Lease> _photoLeases = new();
    private readonly DocumentTextureCacheSystem _visualCache = IoCManager.Resolve<IEntityManager>().System<DocumentTextureCacheSystem>();
    private readonly NewspaperPhotoRequest _photoRequest = new();
    private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    public event Action<NewspaperEdition>? OnSave;
    public event Action<NewspaperEdition>? OnSaveTemplate;
    public event Action<NewspaperEdition>? OnPublish;
    public event Action<int, int>? OnPrint;
    public event Action<int>? OnImageRequested;
    public event Action? OnRemovePhoto;
    public event Action<int>? OnSelectPhoto;
    public event Action<int>? OnForgetPhoto;
    public event Action<NewspaperEdition, int, string>? OnSwitchPublication;

    public NewspaperDeskWindow()
    {
        RobustXamlLoader.Load(this);
        PublicationList.OnItemSelected += args =>
        {
            if (args.Id != _draft.PublicationId)
                OnSwitchPublication?.Invoke(_draft.Clone(), args.Id, "");
        };
        NewPublicationButton.OnPressed += _ =>
        {
            NewPublicationName.Text = _state?.Publications.Length == 1 && string.IsNullOrEmpty(_state.Draft.Name) ? _draft.Name : "";
            NewPublicationToolbar.Visible = true; NewPublicationName.GrabKeyboardFocus();
        };
        CancelPublicationButton.OnPressed += _ => NewPublicationToolbar.Visible = false;
        CreatePublicationButton.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(NewPublicationName.Text)) return;
            OnSwitchPublication?.Invoke(_draft.Clone(), 0, NewPublicationName.Text);
            NewPublicationToolbar.Visible = false;
            NewPublicationName.Text = "";
        };
        DraftModeButton.OnPressed += _ => SetMode(false, false);
        PhotoBufferButton.OnPressed += _ => Refresh();
        BlockSettingsButton.OnPressed += _ => { _pageSettings = false; Refresh(); };
        PageSettingsButton.OnPressed += _ => { _pageSettings = true; Refresh(); };
        RenamePublicationButton.OnPressed += _ => { PublicationNameToolbar.Visible = true; NameField.GrabKeyboardFocus(); };
        CloseNameButton.OnPressed += _ => PublicationNameToolbar.Visible = false;
        UndoButton.OnPressed += _ => RestoreHistory(_undo, _redo);
        RedoButton.OnPressed += _ => RestoreHistory(_redo, _undo);
        ZoomButton.AddItem(Loc.GetString("newspaper-fit-page"), 0);
        foreach (var zoom in new[] { 50, 75, 100, 125 }) ZoomButton.AddItem($"{zoom}%", zoom);
        ZoomButton.SelectId(0);
        ZoomButton.OnItemSelected += args => { _zoom = args.Id; ZoomButton.SelectId(args.Id); };
        FindOverflowButton.OnPressed += _ =>
        {
            var index = PageView.OverflowBlock;
            if (index < 0) return;
            _pageSettings = false;
            _selected = index; _page = _draft.Blocks[index].Page;
            Refresh();
            PageViewport.SetScrollValue(new Vector2(Math.Max(0, _draft.Blocks[index].X * PageView.PreviewScale - 10),
                Math.Max(0, _draft.Blocks[index].Y * PageView.PreviewScale - 10)));
        };
        LinkCaptionButton.OnPressed += _ =>
        {
            if (Selected is not { Kind: NewspaperBlockKind.Text } caption) return;
            var photo = _draft.Blocks.Where(b => b.Kind == NewspaperBlockKind.Photo && b.Page == caption.Page)
                .OrderBy(b => Math.Abs(b.X - caption.X) + Math.Abs(b.Y + b.Height - caption.Y)).FirstOrDefault();
            if (photo == null) return;
            if (photo.Id.Length == 0) photo.Id = Guid.NewGuid().ToString("N");
            caption.CaptionFor = photo.Id;
            caption.Centered = true;
            Refresh();
        };
        // Registered before the BUI close handler so the save is sent while the UI is still open.
        OnClose += SaveIfChanged;
        foreach (var borders in new[] { NewspaperBorders.None, NewspaperBorders.Horizontal, NewspaperBorders.Vertical, NewspaperBorders.All })
            BordersButton.AddItem(Loc.GetString($"newspaper-borders-{borders.ToString().ToLowerInvariant()}"), (int)borders);
        BordersButton.OnItemSelected += args => { if (Selected is {} b) b.Borders = (NewspaperBorders)args.Id; Refresh(); };
        CloseEditorButton.OnPressed += _ => { _selected = -1; Refresh(); };
        _starters = IoCManager.Resolve<IPrototypeManager>().EnumeratePrototypes<NewspaperTemplatePrototype>().OrderBy(p => p.Order).ThenBy(p => p.ID).ToList();
        foreach (var kind in Enum.GetValues<NewspaperBlockKind>())
            AddKindButton.AddItem(Loc.GetString($"newspaper-kind-{kind.ToString().ToLowerInvariant()}"), (int)kind);
        foreach (var font in new[] { NewspaperFont.Serif, NewspaperFont.Sans, NewspaperFont.Cambria })
            FontButton.AddItem(Loc.GetString($"newspaper-font-{font.ToString().ToLowerInvariant()}"), (int)font);
        WeightButton.AddItem(Loc.GetString("newspaper-weight-regular"), 0);
        WeightButton.AddItem(Loc.GetString("newspaper-weight-semibold"), 1);
        WeightButton.AddItem(Loc.GetString("newspaper-weight-bold"), 2);
        WeightButton.OnItemSelected += args => { if (Selected is {} b) b.Font = FontWithWeight(FontFamily(b.Font), args.Id); Refresh(); };
        foreach (var ink in Enum.GetValues<NewspaperInk>())
            InkButton.AddItem(Loc.GetString($"newspaper-ink-{ink.ToString().ToLowerInvariant()}"), (int)ink);
        AddKindButton.SelectId(0);
        BindSpin(PageWidth, 300, 1200, v => { _draft.Width = v; ClampBlocks(); });
        BindSpin(PageHeight, 300, 1200, v => { _draft.Height = v; ClampBlocks(); });
        BindSpin(PageCount, 1, 2, v => { _draft.Pages = v; ClampBlocks(); });
        BindSpin(BlockX, 0, 1200, v => { if (Selected is {} b) { b.CaptionFor = null; b.X = Math.Min(v, _draft.Width - b.Width); } });
        BindSpin(BlockY, 0, 1200, v => { if (Selected is {} b) { b.CaptionFor = null; b.Y = Math.Min(v, _draft.Height - b.Height); } });
        BindSpin(BlockWidth, 1, 1200, v => { if (Selected is {} b) { b.CaptionFor = null; b.Width = Math.Min(v, _draft.Width - b.X); } });
        BindSpin(BlockHeight, 1, 1200, v => { if (Selected is {} b) b.Height = Math.Min(v, _draft.Height - b.Y); });
        BindSpin(BlockPage, 1, 2, v =>
        {
            if (Selected is not {} block) return;
            block.Page = Math.Min(v - 1, _draft.Pages - 1); _page = block.Page;
            if (block.Kind == NewspaperBlockKind.Photo)
                foreach (var caption in _draft.Blocks.Where(c => block.Id.Length > 0 && c.CaptionFor == block.Id)) caption.Page = block.Page;
            else block.CaptionFor = null;
        });
        BindSpin(PhotoSizeField, 32, 1200, value =>
        {
            if (Selected is not { Kind: NewspaperBlockKind.Photo } photo) return;
            var captionSpace = _draft.Blocks.Where(b => b.CaptionFor == photo.Id && photo.Id.Length > 0).Select(b => b.Height + 6).DefaultIfEmpty(0).Max();
            var side = Math.Min(value, Math.Min(_draft.Width - photo.X, _draft.Height - photo.Y - captionSpace));
            photo.Width = photo.Height = Math.Max(1, side);
            NewspaperLayout.ResolvePhotoCaptions(_draft);
        });
        GrayscaleButton.OnToggled += _ => { if (!_loading && Selected is { Kind: NewspaperBlockKind.Photo } photo) { photo.Grayscale = GrayscaleButton.Pressed; Refresh(); } };
        BoldButton.OnPressed += _ => FormatSelection("b");
        ItalicButton.OnPressed += _ => FormatSelection("i");
        BindSpin(FontSizeField, 1, 72, v => { if (Selected is {} b) b.FontSize = v; });
        TemplateList.OnItemSelected += args => { ClearReplacementConfirmation(); _template = args.Id; TemplateList.SelectId(args.Id); Refresh(); };
        BindReplacement(LoadTemplateButton, () =>
        {
            var photo = _draft.PhotoId;
            var loaded = _template < _starters.Count ? CreateStarter(_starters[_template], false) : _state!.Templates[_template - _starters.Count].Clone();
            loaded.PhotoId = photo;
            loaded.Name = _draft.Name; loaded.PublicationId = _draft.PublicationId;
            SetDraft(loaded);
        });
        BindReplacement(BlankButton, () => SetDraft(new NewspaperEdition { Width = _draft.Width, Height = _draft.Height, Pages = _draft.Pages, PhotoId = _draft.PhotoId, Name = _draft.Name, PublicationId = _draft.PublicationId }));
        BindReplacement(DemoButton, () =>
        {
            if (_template >= _starters.Count) return;
            var starter = _starters[Math.Clamp(_template, 0, _starters.Count - 1)];
            var demo = CreateStarter(starter, true);
            demo.PhotoId = _draft.PhotoId;
            demo.PublicationId = _draft.PublicationId;
            if (!string.IsNullOrWhiteSpace(_draft.Name)) demo.Name = _draft.Name;
            SetDraft(demo);
        });
        ModeButton.OnPressed += _ => SetMode(true, false);
        SideButton.OnPressed += _ => { _page = (_page + 1) % Displayed.Pages; Refresh(); };
        RotateButton.OnPressed += _ => { (_draft.Width, _draft.Height) = (_draft.Height, _draft.Width); ClampBlocks(); Refresh(); };
        SnapButton.OnToggled += _ => Refresh();
        SaveTemplateButton.OnPressed += _ =>
        {
            void Save() => OnSaveTemplate?.Invoke(_draft.Clone());
            if (_state!.Templates.Any(t => t.TemplateName == _draft.TemplateName.Trim())) Confirm("newspaper-confirm-template", Save);
            else Save();
        };
        RemovePhotoButton.OnPressed += _ => Confirm("newspaper-confirm-photo", () => OnRemovePhoto?.Invoke());
        PhotoList.OnItemSelected += args =>
        {
            if (!_loading && !_published && args.Id != _draft.PhotoId) OnSelectPhoto?.Invoke(args.Id);
        };
        ForgetPhotoButton.OnPressed += _ =>
        {
            if (!_published && _draft.PhotoId >= 0)
                Confirm("newspaper-photo-forget-confirm", () => OnForgetPhoto?.Invoke(_draft.PhotoId));
        };
        SaveButton.OnPressed += _ => SaveIfChanged();
        PublishButton.OnPressed += _ =>
        {
            _publishPending = true;
            _requestTime = _timing.RealTime;
            _pendingSave = _draft.Clone();
            OnPublish?.Invoke(_draft.Clone());
            Refresh();
        };
        PrintButton.OnPressed += _ => { if (_published && _edition > 0) OnPrint?.Invoke(_count, _edition); };
        DecreaseButton.OnPressed += _ => { _count = Math.Max(1, _count - 1); Refresh(); };
        IncreaseButton.OnPressed += _ => { _count = Math.Min(10, _count + 1); Refresh(); };
        NameField.OnTextChanged += _ => { if (!_loading) { _draft.Name = NameField.Text; Refresh(); } };
        TemplateNameField.OnTextChanged += _ => { if (!_loading) { _draft.TemplateName = TemplateNameField.Text; Refresh(); } };
        TextField.OnTextChanged += _ =>
        {
            if (!_loading && !_published && Selected is {} b)
            {
                b.Text = Rope.Collapse(TextField.TextRope);
                Refresh();
            }
        };
        FontButton.OnItemSelected += args => { if (Selected is {} b) b.Font = FontWithWeight((NewspaperFont)args.Id, FontWeight(b.Font)); Refresh(); };
        InkButton.OnItemSelected += args => { if (Selected is {} b) b.Ink = (NewspaperInk)args.Id; Refresh(); };
        CenterButton.OnToggled += _ => { if (!_loading && Selected is {} b) b.Centered = CenterButton.Pressed; Refresh(); };
        BlockList.OnItemSelected += args =>
        {
            _pageSettings = false; _selected = args.Id;
            if (_selected >= 0) _page = _draft.Blocks[_selected].Page;
            Refresh();
        };
        AddButton.OnPressed += _ =>
        {
            _pageSettings = false;
            if (_draft.Blocks.Count >= NewspaperLayout.MaxBlocks) return;
            var kind = (NewspaperBlockKind)AddKindButton.SelectedId;
            _draft.Blocks.Add(new NewspaperBlock { Id = Guid.NewGuid().ToString("N"), Kind = kind, Page = _page, X = 20, Y = 20, Width = 200, Height = kind == NewspaperBlockKind.Line ? 1 : 100 });
            _selected = _draft.Blocks.Count - 1;
            RefreshBlockList(); Refresh();
        };
        DeleteButton.OnPressed += _ =>
        {
            if (Selected == null) return;
            foreach (var caption in _draft.Blocks.Where(c => c.CaptionFor == Selected.Id && Selected.Id.Length > 0)) caption.CaptionFor = null;
            _draft.Blocks.RemoveAt(_selected);
            _selected = Math.Min(_selected, _draft.Blocks.Count - 1);
            RefreshBlockList(); Refresh();
        };
        DuplicateButton.OnPressed += _ =>
        {
            if (Selected is not {} b || _draft.Blocks.Count >= NewspaperLayout.MaxBlocks) return;
            var copy = b.Clone(); copy.Id = Guid.NewGuid().ToString("N"); copy.CaptionFor = null; copy.X = Math.Min(copy.X + 10, _draft.Width - copy.Width); copy.Y = Math.Min(copy.Y + 10, _draft.Height - copy.Height);
            _draft.Blocks.Add(copy); _selected = _draft.Blocks.Count - 1;
            RefreshBlockList(); Refresh();
        };
        PreviewModeButton.OnPressed += _ => SetMode(false, true);
        ArchiveButton.OnItemSelected += args => { _edition = args.Id + 1; ArchiveButton.SelectId(args.Id); _published = true; Refresh(); };
        PageView.OnSelected += index =>
        {
            _pageSettings = false;
            _selected = index;

            Refresh();
            if (!_layout)
            {
                if (Selected?.Kind == NewspaperBlockKind.PublicationName) { PublicationNameToolbar.Visible = true; NameField.GrabKeyboardFocus(); }
                else if (Selected?.Kind == NewspaperBlockKind.Text) TextField.GrabKeyboardFocus();
            }
        };
        PageView.OnChanged += Refresh;
    }

    private NewspaperBlock? Selected => !_published && _selected >= 0 && _selected < _draft.Blocks.Count ? _draft.Blocks[_selected] : null;
    private NewspaperEdition Displayed => _published && _state != null && _edition > 0 ? _state.Editions[_edition - 1] : _draft;

    private void SetMode(bool layout, bool archive)
    {
        ClearReplacementConfirmation();
        _pageSettings = false;
        _confirmation?.Close();
        _layout = layout; _published = archive;
        PublicationNameToolbar.Visible = NewPublicationToolbar.Visible = false;
        Refresh();
    }

    private bool DraftIsValid() => NewspaperLayout.IsValid(_draft) && (_state == null ||
        !_state.Publications.Any(p => p.Id != _draft.PublicationId &&
            string.Equals(p.Name, _draft.Name.Trim(), StringComparison.OrdinalIgnoreCase)));

    private void SaveIfChanged()
    {
        if (_state == null || !DraftIsValid() || _savedDraft != null && SameDraft(_savedDraft, _draft)) return;
        _requestTime = _timing.RealTime;
        _pendingSave = _draft.Clone();
        OnSave?.Invoke(_draft.Clone());
        Refresh();
    }

    private void BindReplacement(Button button, Action action)
    {
        button.ToolTip = Loc.GetString("newspaper-replace-repeat-tip");
        button.OnPressed += _ =>
        {
            var confirmed = _armedReplacement == button && _timing.RealTime <= _armedUntil;
            ClearReplacementConfirmation();
            if (confirmed) { action(); return; }
            _armedReplacement = button;
            _armedReplacementText = button.Text;
            _armedReplacementMinWidth = button.MinWidth;
            // Preserve the hit target while the confirmation label changes.
            button.MinWidth = Math.Max(button.MinWidth, button.Width);
            _armedUntil = _timing.RealTime + TimeSpan.FromSeconds(2);
            button.Text = Loc.GetString("newspaper-replace-repeat");
        };
    }

    private void ClearReplacementConfirmation()
    {
        if (_armedReplacement != null)
        {
            _armedReplacement.Text = _armedReplacementText;
            _armedReplacement.MinWidth = _armedReplacementMinWidth;
        }
        _armedReplacement = null; _armedReplacementText = null;
    }

    private void Confirm(string key, Action action)
    {
        _confirmation?.Close();
        var publicationId = _draft.PublicationId;
        _confirmation = new DialogWindow(Loc.GetString(key), new());
        _confirmation.OnConfirmed = _ =>
        {
            if (!_published && _draft.PublicationId == publicationId) action();
        };
    }

    private void RestoreHistory(List<NewspaperEdition> source, List<NewspaperEdition> target)
    {
        if (_published || source.Count == 0) return;
        target.Add(_draft.Clone());
        var draft = source[^1]; source.RemoveAt(source.Count - 1);
        draft.PhotoId = _draft.PhotoId; // Physical attachments are owned by the server, not layout history.
        _restoring = true;
        SetDraft(draft);
        _restoring = false;
    }

    private static NewspaperFont FontFamily(NewspaperFont font) => font switch
    {
        NewspaperFont.SansBold => NewspaperFont.Sans,
        NewspaperFont.SerifBold or NewspaperFont.SerifSemibold => NewspaperFont.Serif,
        _ => font,
    };
    private static int FontWeight(NewspaperFont font) => font switch
    {
        NewspaperFont.SansBold or NewspaperFont.SerifBold => 2,
        NewspaperFont.SerifSemibold => 1,
        _ => 0,
    };
    private static NewspaperFont FontWithWeight(NewspaperFont family, int weight) => family switch
    {
        NewspaperFont.Serif when weight == 2 => NewspaperFont.SerifBold,
        NewspaperFont.Serif when weight == 1 => NewspaperFont.SerifSemibold,
        NewspaperFont.Sans when weight > 0 => NewspaperFont.SansBold,
        _ => family,
    };

    private static string PlainText(string text) => string.Concat(NewspaperTypography.ParseStyles(text).Select(c => c.Rune.ToString()));

    private static string ShortText(string text, int limit) => text.Length > limit ? text[..limit] + "…" : text;

    private static string BlockDescription(NewspaperBlock block)
    {
        var text = PlainText(block.Text).Replace('\n', ' ').Trim();
        text = ShortText(text, 22);
        var kind = Loc.GetString($"newspaper-kind-{block.Kind.ToString().ToLowerInvariant()}");
        return $"{kind}: {(text.Length == 0 ? "—" : text)} ({block.Page + 1})";
    }

    private static string EditionHeadline(NewspaperEdition edition) => edition.Blocks
        .Where(b => b.Kind == NewspaperBlockKind.Text && !string.IsNullOrWhiteSpace(b.Text) && b.TextKey == null)
        .OrderByDescending(b => b.FontSize).Select(b => PlainText(b.Text).Replace('\n', ' ')).FirstOrDefault() ?? edition.Name;

    private void BindSpin(SpinBox box, int min, int max, Action<int> action)
    {
        box.IsValid = v => v >= min && v <= max;
        box.InitDefaultButtons();
        box.LineEditControl.MinWidth = 40;
        box.ValueChanged += args => { if (!_loading && !_published) { action(args.Value); Refresh(); } };
    }

    private static NewspaperEdition CreateStarter(NewspaperTemplatePrototype prototype, bool demo)
    {
        var layout = prototype.Layout.Clone();
        layout.TemplateName = Loc.GetString(prototype.Name);
        layout.Name = demo ? Loc.GetString("newspaper-demo-name") : "";
        foreach (var block in layout.Blocks)
        {
            block.Text = block.TextKey != null ? Loc.GetString(block.TextKey) : demo && block.DemoKey != null ? Loc.GetString(block.DemoKey) : block.Text;
        }
        return layout;
    }

    public void UpdateState(NewspaperDeskUiState state)
    {
        var initial = _state == null;
        // Photo and paper updates must not overwrite unsaved local edits.
        var draftChanged = initial || !SameDraft(_state!.Draft, state.Draft);
        var archiveChanged = initial || _state!.Editions.Length != state.Editions.Length;
        var publicationChanged = initial || _state!.Draft.PublicationId != state.Draft.PublicationId;
        var saveAcknowledged = _pendingSave != null && SameDraft(_pendingSave, state.Draft);
        _state = state;
        foreach (var photoId in _photoLeases.Keys.Where(photoId => !state.PhotoKeys.ContainsKey(photoId)).ToArray())
        {
            _photoLeases[photoId].Dispose(); _photoLeases.Remove(photoId); _photos.Remove(photoId);
        }
        _unavailablePhotos.RemoveWhere(id => !state.PhotoKeys.ContainsKey(id));
        if (initial || publicationChanged)
        {
            ClearReplacementConfirmation();
            _confirmation?.Close(); _pendingSave = null; _publishPending = false;
            _undo.Clear(); _redo.Clear(); _checkpoint = null;
        }
        if (draftChanged)
        {
            var draft = state.Draft.Blocks.Count == 0 ? CreateStarter(_starters.FirstOrDefault(p => p.Default) ?? _starters[0], false) : state.Draft.Clone();
            draft.Name = state.Draft.Name; draft.PublicationId = state.Draft.PublicationId;
            // An acknowledgement may arrive after more typing. Keep those newer local edits.
            if (!saveAcknowledged && !SameDraft(_draft, draft)) SetDraft(draft);
            _savedDraft = draft.Clone();
            if (initial || publicationChanged)
            {
                _undo.Clear(); _redo.Clear(); _checkpoint = _draft.Clone();
                _selected = -1;
                PublicationNameToolbar.Visible = false;
            }
        }
        if (saveAcknowledged) { _savedDraft = state.Draft.Clone(); _pendingSave = null; }
        if (_publishPending && archiveChanged && !initial)
        {
            _publishPending = false;
            _published = true; _layout = false;
        }
        _draft.PhotoId = state.Draft.PhotoId;
        TemplateList.Clear();
        var id = 0;
        foreach (var starter in _starters) TemplateList.AddItem(Loc.GetString(starter.Name), id++);
        foreach (var template in state.Templates) TemplateList.AddItem(template.TemplateName, id++);
        _template = Math.Clamp(_template, 0, Math.Max(0, id - 1));
        if (initial || publicationChanged)
        {
            var names = _starters.Select(p => Loc.GetString(p.Name)).Concat(state.Templates.Select(t => t.TemplateName)).ToArray();
            var current = Array.IndexOf(names, _draft.TemplateName);
            if (current >= 0) _template = current;
        }
        TemplateList.SelectId(_template);
        PublicationList.Clear();
        foreach (var publication in state.Publications)
            PublicationList.AddItem(string.IsNullOrEmpty(publication.Name) ? Loc.GetString("newspaper-publication-unnamed") : publication.Name, publication.Id);
        PublicationList.TrySelectId(_draft.PublicationId);
        ArchiveButton.Clear();
        var archive = state.Editions.Select((edition, index) => (Edition: edition, Index: index + 1))
            .Where(e => e.Edition.PublicationId == _draft.PublicationId).ToArray();
        foreach (var entry in archive)
            ArchiveButton.AddItem(Loc.GetString("newspaper-archive-entry", ("edition", entry.Edition.Number), ("headline", ShortText(EditionHeadline(entry.Edition), 48))), entry.Index - 1);
        if (publicationChanged || !archive.Any(e => e.Index == _edition) || archiveChanged && archive.LastOrDefault().Index > _edition)
            _edition = archive.LastOrDefault().Index;
        if (_edition > 0) ArchiveButton.SelectId(_edition - 1);
        Refresh();
    }

    private static bool SameDraft(NewspaperEdition a, NewspaperEdition b) =>
        a.PublicationId == b.PublicationId && a.Name.Trim() == b.Name.Trim() && a.TemplateName.Trim() == b.TemplateName.Trim() && a.Width == b.Width && a.Height == b.Height && a.Pages == b.Pages &&
        a.Blocks.Count == b.Blocks.Count && a.Blocks.Zip(b.Blocks).All(pair =>
            pair.First.Kind == pair.Second.Kind && pair.First.Page == pair.Second.Page && pair.First.X == pair.Second.X && pair.First.Y == pair.Second.Y &&
            pair.First.Width == pair.Second.Width && pair.First.Height == pair.Second.Height && pair.First.Text == pair.Second.Text &&
            pair.First.FontSize == pair.Second.FontSize && pair.First.Font == pair.Second.Font && pair.First.Ink == pair.Second.Ink && pair.First.Centered == pair.Second.Centered && pair.First.Borders == pair.Second.Borders && pair.First.Grayscale == pair.Second.Grayscale && pair.First.Id == pair.Second.Id && pair.First.CaptionFor == pair.Second.CaptionFor);

    private void SetDraft(NewspaperEdition draft)
    {

        _draft = draft; _published = false; _page = 0; _selected = -1;
        _loading = true;
        NameField.Text = draft.Name;
        TemplateNameField.Text = draft.TemplateName;
        _loading = false;
        var templateNames = _starters.Select(p => Loc.GetString(p.Name)).Concat(_state?.Templates.Select(t => t.TemplateName) ?? Enumerable.Empty<string>()).ToArray();
        var templateIndex = Array.IndexOf(templateNames, draft.TemplateName);
        if (templateIndex >= 0) _template = templateIndex;
        RefreshBlockList(); Refresh();
    }

    private void RefreshBlockList()
    {
        BlockList.Clear();
        BlockList.AddItem(Loc.GetString("newspaper-block-none"), -1);
        for (var i = 0; i < _draft.Blocks.Count; i++)
        {
            var b = _draft.Blocks[i];
            BlockList.AddItem(BlockDescription(b), i);
        }
        BlockList.SelectId(_selected);
    }

    private void ClampBlocks()
    {
        _page = Math.Min(_page, _draft.Pages - 1);
        foreach (var b in _draft.Blocks)
        {
            b.Width = Math.Min(b.Width, _draft.Width); b.Height = Math.Min(b.Height, _draft.Height);
            b.X = Math.Min(b.X, _draft.Width - b.Width); b.Y = Math.Min(b.Y, _draft.Height - b.Height);
            b.Page = Math.Min(b.Page, _draft.Pages - 1);
        }
        RefreshBlockList();
    }

    private void FormatSelection(string tag)
    {
        if (_published || Selected?.Kind != NewspaperBlockKind.Text) return;
        var text = Rope.Collapse(TextField.TextRope);
        var start = TextField.SelectionLower.Index;
        var end = TextField.SelectionUpper.Index;
        var formatted = NewspaperTypography.ToggleStyle(text, start, end, tag);
        var updated = formatted.Text;
        if (updated.Length > NewspaperLayout.MaxTextLength) return;
        TextField.TextRope = new Rope.Leaf(updated);
        Selected.Text = updated;
        TextField.CursorPosition = TextField.CursorPosition with { Index = formatted.End };
        TextField.SelectionStart = TextField.SelectionStart with { Index = formatted.Start };
        TextField.GrabKeyboardFocus();
        Refresh();
    }

    private void Refresh()
    {
        if (_loading || _state == null) return;
        _loading = true;
        NewspaperLayout.ResolvePhotoCaptions(_draft);
        if (!_restoring && _checkpoint != null && !SameDraft(_checkpoint, _draft))
        {
            if (_selected >= 0 && _selected < _draft.Blocks.Count && _selected < _checkpoint.Blocks.Count &&
                _checkpoint.Blocks[_selected].CaptionFor != null && _draft.Blocks[_selected].CaptionFor == null)
                _captionNotice = _draft.Blocks[_selected].Id;
            _undo.Add(_checkpoint); if (_undo.Count > 64) _undo.RemoveAt(0);
            _redo.Clear();
        }
        _checkpoint = _draft.Clone();
        _draft.Number = NewspaperLayout.NextEditionNumber(_state.Editions, _draft.PublicationId);
        var shown = Displayed;
        _page = Math.Min(_page, shown.Pages - 1);
        PageView.Editable = !_published;
        PageView.LayoutMode = _layout;
        PageView.Selected = _selected;
        PageView.Snap = SnapButton.Pressed;
        PageView.Page = _page;
        if (!_photos.ContainsKey(shown.PhotoId) && _state.PhotoKeys.TryGetValue(shown.PhotoId, out var photoKey))
        {
            var lease = _visualCache.Photo(photoKey);
            if (lease != null) { _photoLeases[shown.PhotoId] = lease; _photos[shown.PhotoId] = lease.Value.Background; }
        }
        PageView.SetContent(shown, _photos.GetValueOrDefault(shown.PhotoId));
        _photoRequest.SetTarget(shown.PhotoId, _published ? _edition : 0);
        PageWidth.OverrideValue(_draft.Width); PageHeight.OverrideValue(_draft.Height); PageCount.OverrideValue(_draft.Pages);
        if (Selected is {} b)
        {
            BlockList.SelectId(_selected);
            BlockX.OverrideValue(b.X); BlockY.OverrideValue(b.Y); BlockWidth.OverrideValue(b.Width); BlockHeight.OverrideValue(b.Height); BlockPage.OverrideValue(b.Page + 1);
            BordersButton.TrySelectId((int)b.Borders);
            FontSizeField.OverrideValue(b.FontSize); FontButton.SelectId((int)FontFamily(b.Font)); WeightButton.SelectId(FontWeight(b.Font));
            WeightButton.SetItemDisabled(1, FontFamily(b.Font) != NewspaperFont.Serif);
            WeightButton.SetItemDisabled(2, FontFamily(b.Font) == NewspaperFont.Cambria); InkButton.SelectId((int)b.Ink); CenterButton.Pressed = b.Centered;
            if (Rope.Collapse(TextField.TextRope) != b.Text) TextField.TextRope = new Rope.Leaf(b.Text);
            TextProperties.Visible = b.Kind is NewspaperBlockKind.Text or NewspaperBlockKind.PublicationName or NewspaperBlockKind.EditionNumber or NewspaperBlockKind.PageNumber;
            TextInputProperties.Visible = EmphasisToolbar.Visible = SelectionHintLabel.Visible = b.Kind == NewspaperBlockKind.Text;
            PhotoProperties.Visible = b.Kind == NewspaperBlockKind.Photo;
            if (b.Kind == NewspaperBlockKind.Photo) { PhotoSizeField.OverrideValue(b.Width); GrayscaleButton.Pressed = b.Grayscale; }
        }
        // Reserve the editing column throughout both editing modes. Selecting a block does not change zoom.
        EditorSidebar.Visible = !_published;
        EmptySelectionLabel.Visible = Selected == null && (!_layout || !_pageSettings);
        SelectedBlockLabel.Visible = CloseEditorButton.Visible = Selected != null && (!_layout || !_pageSettings);
        if (Selected is {} selected) SelectedBlockLabel.Text = BlockDescription(selected);
        TemplateToolbar.Visible = TemplateSelectionToolbar.Visible = _layout && !_published;
        ArchiveToolbar.Visible = _published && _edition > 0;
        ArchiveEmptyLabel.Visible = _published && _edition == 0;
        PageViewport.Visible = !_published || _edition > 0;
        DraftActions.Visible = !_published;
        PrintActions.Visible = _published;
        DraftModeButton.Pressed = !_published && !_layout;
        ModeButton.Pressed = !_published && _layout;
        PreviewModeButton.Pressed = _published;
        UndoButton.Visible = RedoButton.Visible = !_published;
        UndoButton.Disabled = _undo.Count == 0;
        RedoButton.Disabled = _redo.Count == 0;
        DemoButton.Disabled = _template >= _starters.Count;
        DemoButton.ToolTip = Loc.GetString("newspaper-replace-repeat-tip");
        SaveTemplateButton.ToolTip = Loc.GetString("newspaper-template-content-tip");
        SidebarModeToolbar.Visible = _layout && !_published;
        BlockSettingsButton.Pressed = !_pageSettings;
        PageSettingsButton.Pressed = _pageSettings;
        BlockList.Visible = BlockListLabel.Visible = _layout && !_pageSettings;
        BlockProperties.Visible = Selected != null && (!_layout || !_pageSettings);
        BordersButton.Visible = _layout;
        GeometryFields.Visible = _layout;
        PageProperties.Visible = _layout && !_published && _pageSettings;
        BlockList.Disabled = _published || _draft.Blocks.Count == 0;
        NameField.Editable = TemplateNameField.Editable = !_published;
        LoadTemplateButton.Disabled = BlankButton.Disabled = _published;
        DemoButton.Disabled = _published || _template >= _starters.Count;
        RenamePublicationButton.Disabled = _published;
        SideLabel.Text = Loc.GetString("newspaper-side-status", ("page", _page + 1), ("pages", shown.Pages));
        SideButton.Visible = shown.Pages > 1;
        SideButton.Text = Loc.GetString(_page == 1 ? "newspaper-show-front" : "newspaper-show-back");
        PreviewLabel.Text = Loc.GetString(_published ? "newspaper-published-preview" : "newspaper-draft-preview");
        ArchiveButton.Disabled = _edition == 0;
        RemovePhotoButton.Disabled = _published || _draft.PhotoId < 0;
        PhotoBufferButton.Disabled = _published;
        PhotoBufferToolbar.Visible = PhotoBufferButton.Pressed && !_published;
        PhotoList.Clear();
        PhotoList.AddItem(Loc.GetString("newspaper-photo-none"), -1);
        foreach (var id in _state.BufferedPhotos)
            PhotoList.AddItem(Loc.GetString("newspaper-photo-entry", ("id", id)), id);
        if (_draft.PhotoId >= 0 && !_state.BufferedPhotos.Contains(_draft.PhotoId))
            PhotoList.AddItem(Loc.GetString("newspaper-photo-entry", ("id", _draft.PhotoId)), _draft.PhotoId);
        PhotoList.TrySelectId(_draft.PhotoId);
        PhotoList.Disabled = _published;
        ForgetPhotoButton.Disabled = _published || !_state.BufferedPhotos.Contains(_draft.PhotoId);
        var valid = DraftIsValid();
        var dirty = _savedDraft == null || !SameDraft(_savedDraft, _draft);
        SaveButton.Disabled = _published || !valid || !dirty;
        SaveStatusLabel.Text = Loc.GetString(_published ? "newspaper-archive-status" : !valid ? "newspaper-save-invalid" :
            _pendingSave != null ? "newspaper-saving" : dirty ? "newspaper-unsaved" : "newspaper-saved");
        SaveStatusLabel.ToolTip = Loc.GetString("newspaper-close-save-tip");
        SaveTemplateButton.Disabled = _published || !valid || string.IsNullOrWhiteSpace(_draft.TemplateName);
        OverflowToolbar.Visible = !_published && !PageView.ContentFits;
        if (OverflowToolbar.Visible)
            OverflowLabel.Text = Loc.GetString("newspaper-block-overflow", ("block", PageView.OverflowBlock + 1));
        var contentValid = valid && NewspaperLayout.IsValid(_draft, true);
        var lastEdition = _state.Editions.LastOrDefault(e => e.PublicationId == _draft.PublicationId);
        var alreadyPublished = lastEdition != null && SameDraft(lastEdition, _draft) && lastEdition.PhotoId == _draft.PhotoId;
        PublishButton.Disabled = _published || _publishPending || alreadyPublished || !contentValid || !PageView.ContentFits;
        PublishButton.ToolTip = Loc.GetString(alreadyPublished ? "newspaper-publish-unchanged-tip" : !contentValid ? "newspaper-publish-content-tip" : !PageView.ContentFits ? "newspaper-publish-overflow-tip" : "newspaper-publish-tip");
        PrintButton.ToolTip = Loc.GetString(_edition == 0 ? "newspaper-archive-empty" : _state.PaperCount < _count ? "newspaper-print-paper-tip" : "newspaper-print-tip");
        CaptionLinkLabel.Visible = (!_layout || !_pageSettings) && (Selected?.CaptionFor != null || Selected != null && Selected.Id == _captionNotice);
        CaptionLinkLabel.Text = Loc.GetString(Selected?.CaptionFor != null ? "newspaper-caption-linked" : "newspaper-caption-unlinked");
        LinkCaptionButton.Visible = _layout && !_pageSettings && Selected is { Kind: NewspaperBlockKind.Text, CaptionFor: null } &&
            _draft.Blocks.Any(b => b.Kind == NewspaperBlockKind.Photo && b.Page == Selected.Page);
        PrintButton.Disabled = !_published || _edition == 0 || _state.PaperCount < _count;
        PrintButton.Text = _edition > 0 ? Loc.GetString("newspaper-print-edition", ("edition", _state.Editions[_edition - 1].Number)) : Loc.GetString("newspaper-print");
        PaperLabel.Text = Loc.GetString("newspaper-paper-count", ("count", _state.PaperCount));
        CountLabel.Text = _count.ToString();
        _loading = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_armedReplacement != null && (_timing.RealTime > _armedUntil || _armedReplacement.Disabled || !_layout || _published))
            ClearReplacementConfirmation();
        if ((_pendingSave != null || _publishPending) && _timing.RealTime - _requestTime > TimeSpan.FromSeconds(5))
        {
            _pendingSave = null; _publishPending = false;
            Refresh();
        }
        if (_state != null && PageViewport.Width > 0 && PageViewport.Height > 0)
        {
            var shown = Displayed;
            PageView.PreviewScale = _zoom == 0
                ? Math.Clamp(Math.Min((PageViewport.Width - 20) / shown.Width, (PageViewport.Height - 20) / shown.Height), 0.1f, 1f)
                : _zoom / 100f;
        }
        if (VisibleInTree && _photoRequest.TryRequest(_timing.RealTime, _photos.ContainsKey(_photoRequest.PhotoId) || _unavailablePhotos.Contains(_photoRequest.PhotoId), out var edition))
            OnImageRequested?.Invoke(edition);
    }

    public void ReceivePhoto(int photoId, byte[] data, string photoKey = "")
    {
        try
        {
            var key = photoKey.Length > 0 ? photoKey : _state?.PhotoKeys.GetValueOrDefault(photoId);
            if (string.IsNullOrEmpty(key)) return;
            var lease = _visualCache.Photo(key, data);
            if (lease == null) { _unavailablePhotos.Add(photoId); return; }
            _photoLeases.GetValueOrDefault(photoId)?.Dispose();
            _photoLeases[photoId] = lease;
            _photos[photoId] = lease.Value.Background;
            Refresh();
        }
        catch (Exception e) { _unavailablePhotos.Add(photoId); Logger.ErrorS("newspaper", $"Cannot load newspaper photo: {e.Message}"); }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _confirmation?.Close();
            foreach (var lease in _photoLeases.Values) lease.Dispose();
        }
        base.Dispose(disposing);
    }
}
