using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.ResourceExtractor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Forge.ResourceExtractor.UI;

[GenerateTypedNameReferences]
public sealed partial class ResourceExtractorWindow : FancyWindow
{
    private const int ProgressSegments = 20;
    private const int PercentPerSegment = 5;
    private static readonly Color TerminalGreen = Color.FromHex("#38e64c");
    private static readonly Color TerminalMutedGreen = Color.FromHex("#238a32");
    private static readonly Color TerminalBackgroundColor = Color.FromHex("#070a07");
    private static readonly Color TerminalButtonColor = Color.FromHex("#101a10");
    private static readonly Color TerminalDisabledColor = Color.FromHex("#0a0e0a");

    public event Action? OnStart;
    public event Action? OnStop;
    public event Action? OnEjectFuel;
    public event Action? OnOpenOutput;

    public ResourceExtractorWindow()
    {
        RobustXamlLoader.Load(this);

        StartButton.OnPressed += _ => OnStart?.Invoke();
        StopButton.OnPressed += _ => OnStop?.Invoke();
        EjectFuelButton.OnPressed += _ => OnEjectFuel?.Invoke();
        OpenOutputButton.OnPressed += _ => OnOpenOutput?.Invoke();

        TerminalBackground.PanelOverride = CreateBox(TerminalBackgroundColor, TerminalMutedGreen, 1);

        SetTerminalText(StatusTitleLabel, FuelTitleLabel, ProgressTitleLabel,
            StatusLabel, FuelLabel, AsciiProgressLabel, PendingLabel);
        ConfigureTerminalButton(StartButton);
        ConfigureTerminalButton(StopButton);
        ConfigureTerminalButton(OpenOutputButton);
        ConfigureTerminalButton(EjectFuelButton);
    }

    public void UpdateState(ResourceExtractorUiState state)
    {
        StatusLabel.Text = Loc.GetString(GetStatusLocKey(state.Status));
        var fuelPercent = Math.Clamp(
            (int) MathF.Floor(state.FuelFraction * 100f + 0.0001f),
            0,
            100);
        FuelLabel.Text = Loc.GetString("resource-extractor-fuel-value", ("percent", fuelPercent));

        var duration = Math.Max(0.001f, state.DurationSeconds);
        var progress = Math.Clamp(state.ProgressSeconds / duration, 0f, 1f);
        var percent = Math.Clamp((int) MathF.Floor(progress * 100f + 0.0001f), 0, 100);
        var filledSegments = Math.Clamp(percent / PercentPerSegment, 0, ProgressSegments);
        AsciiProgressLabel.Text =
            $"[{new string('#', filledSegments)}{new string('-', ProgressSegments - filledSegments)}] {percent,3}%";

        PendingLabel.Visible = state.PendingUnits > 0;
        PendingLabel.Text = Loc.GetString(
            "resource-extractor-pending-value",
            ("units", state.PendingUnits));

        StartButton.Disabled = state.UserEnabled || state.Status == ResourceExtractorStatus.Running;
        StopButton.Disabled = !state.UserEnabled && state.Status != ResourceExtractorStatus.Running;
        // Keep draining available for an empty-looking tank: it may contain an
        // incompatible liquid that has clogged the fuel system.
        EjectFuelButton.Disabled = false;
        ApplyButtonState(StartButton);
        ApplyButtonState(StopButton);
        ApplyButtonState(OpenOutputButton);
        ApplyButtonState(EjectFuelButton);
    }

    private static void SetTerminalText(params Label[] labels)
    {
        foreach (var label in labels)
        {
            label.AddStyleClass("monospace");
            label.FontColorOverride = TerminalGreen;
        }
    }

    private static void ConfigureTerminalButton(Button button)
    {
        button.Label.AddStyleClass("monospace");
        button.Label.FontColorOverride = TerminalGreen;
        ApplyButtonState(button);
    }

    private static void ApplyButtonState(Button button)
    {
        var background = button.Disabled ? TerminalDisabledColor : TerminalButtonColor;
        var foreground = button.Disabled ? TerminalMutedGreen : TerminalGreen;
        button.StyleBoxOverride = CreateBox(background, foreground, 1);
        button.Label.FontColorOverride = foreground;
    }

    private static StyleBoxFlat CreateBox(Color background, Color border, int thickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(thickness),
        };
    }

    private static string GetStatusLocKey(ResourceExtractorStatus status)
    {
        return status switch
        {
            ResourceExtractorStatus.Running => "resource-extractor-status-running",
            ResourceExtractorStatus.NoFuel => "resource-extractor-status-no-fuel",
            ResourceExtractorStatus.OutputFull => "resource-extractor-status-output-full",
            ResourceExtractorStatus.Clogged => "resource-extractor-status-clogged",
            ResourceExtractorStatus.Unanchored => "resource-extractor-status-unanchored",
            ResourceExtractorStatus.InvalidConfiguration => "resource-extractor-status-invalid-configuration",
            ResourceExtractorStatus.ProcessingOutput => "resource-extractor-status-processing-output",
            _ => "resource-extractor-status-off",
        };
    }
}
